"""
Django settings for day06 project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@h471(hw6(8g7grvph3l4n87&7d*f4z4i=70e=)594=dr2dh36'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    # 'django.contrib.auth',
    # 'django.contrib.contenttypes',
    # 'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web.apps.WebConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'utils.md.AuthMiddleWare',
]

ROOT_URLCONF = 'day06.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                # 'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'day06.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'day06',
        'USER': 'root',
        "PASSWORD": '668034ky',
        'HOST': '127.0.0.1',
        'POST': 3306,
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#cache配置
CACHES = {
    "default" : {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100}
        }
    }
}
#sessions配置
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7 # 一周

LOGIN_HOME = '/home/'
M_DIRECT_VISIT = ['/login/','/sms/login/','/sms/send/']
M_USERINFO = 'user_info'
M_LOGIN = '/login/'


M_MENU = {
    "ADMIN": [
        {
            'text':'用户信息',
            'icon':'fa-keyboard-o',
            'children':[
                {'text':'级别管理', 'url': '/level/list/', 'name':'level_list'},
                {'text':'客户列表', 'url': '/customer/list/', 'name':'customer_list'},
                {'text':'价格策略', 'url': '/policy/list/', 'name':'policy_list'},
            ]
        },
        {
            'text':'订单管理',
            'icon':'fa-keyboard-o',
            'children':[
                {'text':'订单信息', 'url': '/transaction/list/', 'name':'transaction_list'},
            ]
        },
    ],
    "CUSTOMER": [
        {
            'text': '订单中心',
            'icon': 'fa-bed',
            'children': [
                {'text':'订单管理', 'url': '/my/order/list/', 'name':'my_order_list'},
                {'text':'我的订单', 'url': '/my/transaction/list/', 'name':'my_transaction_list'},
            ]
        },
    ],
}

M_PREMISSION_PUBLIC = {
    'home': {'text': '主页', 'parent': None},
    'logout': {'text':'注销','parent': None},
}

M_PREMISSION = {
    'ADMIN':{
        'level_list':{'text':'级别列表','parent':None},
        'level_add':{'text':'新增级别','parent':'level_list'},
        'level_edit':{'text':'编辑级别','parent':'level_list'},
        'level_delete':{'text':'删除级别','parent':'level_list'},

        'customer_list':{'text':'客户列表','parent':None},
        'customer_add':{'text':'新增客户','parent':'customer_list'},
        'customer_edit':{'text':'编辑客户','parent':'customer_list'},
        'customer_reset':{'text':'重置密码','parent':'customer_list'},
        'customer_delete':{'text':'删除客户','parent':'customer_list'},
        'customer_charge':{'text':'我的交易记录','parent':'customer_list'},
        'customer_charge_add':{'text':'我的交易记录','parent':'customer_list'},

        'policy_list':{'text':'价格策略列表','parent':None},
        'policy_add':{'text':'新增策略列表','parent':'policy_list'},
        'policy_edit':{'text':'编辑策略列表','parent':'policy_list'},
        'policy_delete':{'text':'删除策略列表','parent':'policy_list'},

        'transaction_list':{'text':'客户订单列表','parent':None},
    },
    'CUSTOMER':{
         'my_order_list':{'text':'订单列表','parent':None},
         'my_order_add':{'text':'创建订单','parent':'my_order_list'},
         'my_order_cancel':{'text':'创建订单','parent':'my_order_list'},
         'my_transaction_list':{'text':'我的订单列表','parent':None},

    }
}

QUEUE_TASK_NAME = "YANG_TASK_QUEUE"

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

MESSAGE_DANGER_TAG = 50
MESSAGE_TAGS = {
    MESSAGE_DANGER_TAG: "danger"
}