# Generated by Django 3.2 on 2024-06-25 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_order_pricepolicy_transactionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(db_index=True, max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', '手机号格式错误')], verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='level',
            name='precent',
            field=models.IntegerField(help_text='填入0-100整数表示百分比，例如90，表示90%', verbose_name='折扣'),
        ),
    ]
